defaults:
  - cache: file_cache

_target_: stopes.core.Launcher
log_folder: executor_logs
cluster: slurm
partition: ust,learnaccel,learnfair
max_jobarray_jobs: 1000
throttle:
  shared_name: /launcher_${oc.env:USER}
  limit: 256
  timeout: null
